# View goreleaser docs for configuration settings
# https://goreleaser.com

---
project_name: pgreplay

builds:
  - binary: pgreplay
    main: cmd/pgreplay/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: >
      -X main.Version={{.Version}}
      -X main.Commit={{.Commit}}
      -X main.Date={{.Date}}
      -a
      -installsuffix cgo
    env:
      - CGO_ENABLED=0

